# Generated by Django 2.0.13 on 2019-10-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_simple'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simple',
            new_name='Name',
        ),
    ]
