# Generated by Django 2.0.13 on 2019-10-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_group_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='time',
        ),
        migrations.AlterField(
            model_name='group',
            name='people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.IntegerField(),
        ),
    ]
