# Generated by Django 2.0.13 on 2019-10-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191003_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='hour',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='minute',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
