# Generated by Django 2.0.13 on 2019-10-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191003_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
